timeout: 2400s
steps:
  # Install evervault CLI
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl https://cage-build-assets.evervault.com/cli/install -sL | sh
        echo $$EV_CAGE_KEY > key.pem
        echo $$EV_CAGE_CERT > cert.pem
        cat key.pem
        cat cert.pem
        ls
        ev-cage deploy --signing-cert cert.pem --private-key key.pem
    secretEnv: ['EV_API_KEY', 'EV_CAGE_KEY', 'EV_CAGE_CERT']
availableSecrets:
  secretManager:
  - versionName: projects/402677045867/secrets/EV_API_KEY/versions/latest
    env: 'EV_API_KEY'
  - versionName: projects/402677045867/secrets/EV_CAGE_KEY/versions/latest
    env: 'EV_CAGE_KEY'
  - versionName: projects/402677045867/secrets/EV_CAGE_CERT/versions/latest
    env: 'EV_CAGE_CERT'